"""Read a delivered data file, wherever it is served from.

Document shards live in object storage; everything else is served by the site from
public/data. Validators need the bytes either way, so they go through here rather than each
deciding for itself where a file lives.

public/data/delivery.json is generated by build-catalog.py and carries both the base URL per
format and the prefixes that mark a path as a shard, so this module never restates the
classification rule.

Two ways to reach object storage:

  S3 API    used when R2 credentials are present. Authenticated, not rate limited, and the
            right channel for a validator that reads thousands of objects in one run.
  HTTPS     the public delivery URL, used otherwise. Cloudflare rate limits r2.dev and
            answers a bare urllib agent with an error 1010 challenge, so requests carry a
            real agent and retry with backoff on 429 and 5xx.
"""
import json
from fnmatch import fnmatch
import os
import random
import time
import urllib.error
import urllib.request
from pathlib import Path

from common import PUBLIC, load_env

# Cloudflare answers the default urllib agent with an error 1010 challenge.
AGENT = "anton-portfolio-validator (+https://github.com/korv9/anton-portfolio)"
RETRIES = 5

_manifest = json.loads((PUBLIC / "delivery.json").read_text(encoding="utf-8"))
BASES = _manifest["bases"]
SHARD_PREFIXES = tuple(_manifest["shard_prefixes"])

_s3 = None


def is_shard(relative: str) -> bool:
    """True for a path served from object storage. Mirrors build-catalog.py via the manifest."""
    return relative.startswith(SHARD_PREFIXES) and not relative.endswith("/index.json")


def _bucket_client():
    """A boto3 client and bucket name, or None when credentials are not configured."""
    global _s3
    if _s3 is None:
        try:
            import boto3
        except ImportError:
            _s3 = False
            return None
        load_env()
        needed = ("R2_ACCOUNT_ID", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY", "R2_BUCKET")
        if not all(os.environ.get(name) for name in needed):
            _s3 = False
            return None
        endpoint = os.environ.get("S3_API_ENDPOINT") or \
            f"https://{os.environ['R2_ACCOUNT_ID']}.r2.cloudflarestorage.com"
        bucket = os.environ["R2_BUCKET"]
        _s3 = (boto3.client("s3", endpoint_url=endpoint.rstrip("/").removesuffix("/" + bucket),
                            aws_access_key_id=os.environ["R2_ACCESS_KEY_ID"],
                            aws_secret_access_key=os.environ["R2_SECRET_ACCESS_KEY"],
                            region_name="auto"), bucket)
    return _s3 or None


def fetch(relative: str) -> bytes:
    client = _bucket_client()
    if client:
        s3, bucket = client
        # The streaming body holds a connection. A build reading hundreds of objects that
        # never closes them exhausts the process's handles, and the next unrelated open()
        # fails with EINVAL.
        body = s3.get_object(Bucket=bucket, Key=relative)["Body"]
        try:
            return body.read()
        finally:
            body.close()

    request = urllib.request.Request(BASES["shard"] + relative, headers={"User-Agent": AGENT})
    for attempt in range(RETRIES):
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                return response.read()
        except urllib.error.HTTPError as error:
            retryable = error.code == 429 or 500 <= error.code < 600
            if not retryable or attempt == RETRIES - 1:
                raise
            # Full jitter, because every worker backs off from the same rate limit at once.
            time.sleep(random.uniform(0, 2 ** attempt))
    raise RuntimeError(f"Unreachable: {relative}")


def catalogue_paths(pattern: str) -> list[str]:
    """Delivered paths matching a glob, from the catalogue rather than the filesystem.

    Globbing public/data only sees what is still local, so a build that enumerates sources
    that way silently produces an empty result once those files move to object storage.
    The catalogue is the record of what exists, wherever it is served from.
    """
    catalogue = json.loads((PUBLIC / "catalog.json").read_text(encoding="utf-8"))
    return sorted(entry["path"] for entry in catalogue["files"]
                  if fnmatch(entry["path"], pattern))


def read_bytes(relative: str) -> bytes:
    """Bytes for a path relative to public/data: local if present, else from delivery."""
    path = Path(PUBLIC) / relative
    return path.read_bytes() if path.is_file() else fetch(relative)
