import { test, expect } from '@playwright/test'

test('project reports expose published results and complete imported tables', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/#product-directory')
  await expect(page.locator('.product-cards > article')).toHaveCount(6)
  const drugcomb = page.locator('#drugcomb')
  await expect(drugcomb).toContainText('396,498')
  await expect(drugcomb.locator('[role="img"]')).toHaveCount(4)
  const initial = await drugcomb.locator('.research-bars').first().innerText()
  await drugcomb.getByLabel('Feature set / model').selectOption('history_ridge')
  await expect(drugcomb.locator('.research-bars').first()).not.toHaveText(initial)
  const desk = page.locator('#data-explorer')
  await expect(desk.getByRole('combobox', { name: 'Dataset', exact: true }).locator('option')).toHaveCount(53)
  await expect(desk.locator('tbody tr')).toHaveCount(25)
  await expect(desk).toContainText('1,104 matching rows of 1,104')
  await desk.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(desk.locator('.table-pagination')).toContainText('Page 2')
  await desk.getByRole('button', { name: 'All decision points', exact: true }).click()
  await expect(desk.locator('caption')).toHaveText('fact decision point')
  await expect(desk).toContainText('4,407 matching rows of 4,407')
  await expect(desk.locator('.table-pagination')).toContainText('Page 1')
  await expect(desk.getByRole('link', { name: 'Download full JSON' })).toHaveAttribute('href', /fact_decision_point/)
  await desk.getByLabel('Search all columns').fill('no-such-record-unique-query')
  await expect(desk).toContainText('No rows match these filters.')
  await desk.getByRole('button', { name: 'DrugComb evaluations' }).click()
  await expect(desk.locator('caption')).toHaveText('metrics')
  await desk.getByRole('combobox', { name: 'Evaluation split', exact: true }).selectOption('cold_drug')
  await expect(desk.locator('tbody tr')).toHaveCount(8)
  await expect(desk.getByRole('link', { name: 'Original CSV' })).toHaveAttribute('href', /metrics.csv$/)
  expect(errors).toEqual([])
})
