"""Assemble ``reports/REPORT.md`` from the generated tables and figures."""

from __future__ import annotations

import json
import logging

import pandas as pd

from .config import Paths
from .figures import MODEL_LABELS, SCHEME_LABELS

log = logging.getLogger(__name__)


def _md_table(df: pd.DataFrame, floatfmt: str = ".3f") -> str:
    def fmt(v):
        if isinstance(v, float):
            return format(v, floatfmt)
        return str(v)

    head = "| " + " | ".join(df.columns) + " |"
    sep = "| " + " | ".join("---" for _ in df.columns) + " |"
    body = ["| " + " | ".join(fmt(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([head, sep, *body])


def _fig(paths: Paths, name: str, alt: str) -> str:
    return f"![{alt}](figures/{name}.png)\n" if (paths.figures / f"{name}.png").exists() else ""


def _read(paths: Paths, name: str) -> pd.DataFrame | None:
    p = paths.tables / name
    return pd.read_csv(p) if p.exists() else None


def build_report(paths: Paths) -> str:
    out = ["# DrugCombDB synergy – results report", ""]
    out.append("_Generated by `drugsyn report` – do not edit by hand._\n")

    if paths.manifest.exists():
        man = pd.DataFrame(json.loads(paths.manifest.read_text()))
        man["sha256"] = man["sha256"].str[:12] + "…"
        man["MB"] = (man["bytes"] / 1e6).round(1)
        out += ["## Data provenance", "",
                _md_table(man[["source", "file", "release", "MB", "sha256", "recorded_at"]]), ""]

    kpi = _read(paths, "sql_kpi_overview.csv")
    if kpi is not None:
        out += ["## Dataset at a glance", "", _md_table(kpi.T.reset_index().set_axis(
            ["metric", "value"], axis=1), ".4g"), ""]

    out += ["## Data engineering", ""]
    out.append(_fig(paths, "de_01_data_funnel", "Cleaning funnel"))
    out.append(_fig(paths, "de_02_entity_resolution", "Entity resolution coverage"))
    qc = _read(paths, "data_quality.csv")
    if qc is not None:
        out += ["### Data-quality checks", "", _md_table(qc), ""]

    out += ["## Exploratory analysis", ""]
    for name, alt in [
        ("an_01_zip_distribution", "ZIP distribution"),
        ("an_02_replicate_agreement", "Replicate agreement"),
        ("an_03_score_concordance", "Score concordance"),
        ("an_04_synergy_by_lineage", "Synergy by lineage"),
        ("an_05_screen_coverage", "Screen coverage"),
        ("an_06_top_pairs", "Top synergistic pairs"),
        ("an_07_cell_landscape", "Cell-line landscape"),
        ("an_08_synergy_by_study", "Synergy by study"),
    ]:
        out.append(_fig(paths, name, alt))

    metrics = _read(paths, "metrics.csv")
    if metrics is not None:
        out += ["## Modelling", ""]
        out.append(_fig(paths, "ml_01_performance_by_split", "Performance by split"))
        t = metrics.assign(
            split=metrics["scheme"].map(SCHEME_LABELS),
            model=metrics["model"].map(MODEL_LABELS),
        )[["split", "model", "pearson", "spearman", "rmse", "r2", "auprc_synergy",
           "prevalence_synergy"]]
        out += [_md_table(t), ""]
        out.append(_fig(paths, "ml_02_feature_families", "Feature families"))
        out.append(_fig(paths, "ml_03_pred_vs_obs", "Predicted vs observed"))
        out.append(_fig(paths, "ml_04_ablation", "Ablation"))
        out += ["## Model diagnostics", ""]
        for name, alt in [("ml_05_overfitting", "Overfitting check"),
                          ("ml_06_enrichment", "Enrichment"),
                          ("ml_07_calibration", "Calibration")]:
            out.append(_fig(paths, name, alt))
        for table, title in [("eval_y_scramble.csv", "Y-scramble (leakage check)"),
                             ("eval_by_study.csv", "Performance by study"),
                             ("eval_enrichment.csv", "Enrichment of synergistic hits")]:
            t = _read(paths, table)
            if t is not None and len(t):
                out += [f"### {title}", "", _md_table(t), ""]
    return "\n".join(out)


def run(cfg: dict, paths: Paths) -> None:
    paths.ensure()
    if paths.manifest.exists():  # versioned copy of the provenance record
        (paths.reports / "data_manifest.json").write_text(paths.manifest.read_text())
    text = build_report(paths)
    (paths.reports / "REPORT.md").write_text(text, encoding="utf-8")
    log.info("report written to %s", paths.reports / "REPORT.md")
